version: '3'
services:

########################
# Setup express server container
########################
  server:
    build: 
      context: ./server
      dockerfile: DockerFile
    expose:
      - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    # volumes:
    #   - ./server/src:/srv/app/server/src
    command: npm start


########################
# Setup client container
########################
  client:
    build: 
      context: ./client
      dockerfile: DockerFile
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    links:
      - server
     
    command: npm start
    